### ISSUE TITLE
in game title image and tool back ground display corrupted

### ISSUE THREAD

**Issue by ghost** [DaeFennek/wii-voxel-engine#3]
other images such as single player, multiplayer, options and exit are fine.  seems to be a png issue.  tested on real hardware.

**Comment by kperdlich** [comment]
Tried to fix it. Could you please try again with the current .dol from the repo?

**Comment by ghost** [comment]
Yes, it works perfect fine now.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Kevin PerdlichSent: Saturday, September 16, 2017 6:12 PMTo: DaeFennek/wii-voxel-engineReply To: DaeFennek/wii-voxel-engineCc: owen; AuthorSubject: Re: [DaeFennek/wii-voxel-engine] in game title image and tool back ground display corrupted (#3)Tried to fix it. Could you please try again with the current .dol from the repo?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DaeFennek/wii-voxel-engine","title":"DaeFennek/wii-voxel-engine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DaeFennek/wii-voxel-engine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DaeFennek in #3: Tried to fix it. Could you please try again with the current .dol from the repo?"}],"action":{"name":"View Issue","url":"https://github.com/DaeFennek/wii-voxel-engine/issues/3#issuecomment-330000432"}}}
