### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by NiHuShu** [DaeFennek/wii-voxel-engine#4]
On real Wii i can't move camera down with wiimote also please add option to move camera with dpad

**Comment by Tovl02** [comment]
I've been having this same issue on Dolphin
I didn't report it because the issue might not be on console, but seeing as another fine individual had this issue on console, I thought I'd report it now

**Comment by kperdlich** [comment]
I only noticed that sometimes if you move the wimote too fast it kind of stucks but if you move it slowly it works fine for me on Wii and in Dolphin

**Comment by lorenzsandi** [comment]
I played this game on real hardware and noticed that moving the cursor was a little hard and sticks towards the edges of the screen half the time. It would be cool to see classic controller support, or a creative mode style inventory to select a block, and survival mode.

**Comment by lorenzsandi** [comment]
I found out that when holding a direction on the nunchuck and unpluging it while in game, it will move in that direction and jitter to the side, When I held left and unpluged it, it moved left while jutting forward slightly and looks jittery when it's unpluged.

**Comment by kperdlich** [comment]
I'll not work on this project any further
