### ISSUE TITLE
Support the latest Minecraft version

### ISSUE THREAD

**Issue by Heath123** [DaeFennek/wii-voxel-engine#7]
Please update this, at least to a version compatible with ProtocolSupport so ot xan be used with modern servers.

**Comment by iyenal** [comment]
Well looks like _wii-voxel-engine/src/net_ have all the code related to network communications, so maybe we can do

**Comment by lorenzsandi** [comment]
that'd be cool

**Comment by kperdlich** [comment]
I'll not continue working on this project.
